version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.dev
    restart: unless-stopped
    volumes:
      - '.:/app'
    ports:
      - 5173:5173
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/ &&
      pnpm dev --host 0.0.0.0"
