version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile.dev
    restart: unless-stopped
    volumes:
      - ./node_modules:/app/node_modules
      - .:/app/pnpm-lock.yaml
    develop:
      watch:
        - action: sync
          path: .
          target: /app
        - action: rebuild
          path: package.json
        - action: sync+restart
          path: vite.config.ts
    ports:
      - 5173:5173
    command: >
      bash -c "cp -rfu /cache/node_modules/. /app/node_modules/ &&
      cp /cache/pnpm-lock.yaml /app/pnpm-lock.yaml &&
      pnpm dev --host 0.0.0.0"
