FROM node:18.19.0

# Create and define the node_modules's cache directory.
WORKDIR /cache

# enable PNPM
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# install app dependencies
COPY package.json .
RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install

# set working directory add `/app/node_modules/.bin` to $PATH
WORKDIR /app
ENV PATH="/app/node_modules/.bin:$PATH"

# copy source code
COPY . .